/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client/public/Drone.glb --transform --types 
Files: client/public/Drone.glb [259.68KB] > C:\Users\Dj Praveen Kumawat\Desktop\AeroMake-Marketplace (1)\AeroMake-Marketplace\Drone-transformed.glb [21.92KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh
  }
  materials: {
    ColourPalette: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Drone-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.ColourPalette} />
    </group>
  )
}

useGLTF.preload('/Drone-transformed.glb')
